### ISSUE TITLE
Bcrypt Question

### ISSUE THREAD

**Issue by Loader23** [tomsquest/docker-radicale#14]
Hi,

first things first: Thank you!
I set it up today and its working perfect, thanks alot! 👍

I guess you does not see any comments on closed Issues so I open a new one. More a question than an issue:

How did you configure bcrypt? The Documentation says to use htpasswd but with the command "docker exec radicale htpasswd" it gives me a executable file not found error. Is it even possible to configure bcrypt with the Docker Container? Iam currently using crypt but since it is only working but not secure I would like to switch to bcrypt.
And how do you use SSL Certs? I tried to make a volume for it but Radicale does not find the certs. But the volume is mounted, I can see this via SSH.

Than another thing: I saw your config file. Do you even use bcrypt? You changed authentication to none which seems weird to me.
You also changed "filesystem_folder = /data/collections". My Radicale created a "collection-root" folder, so my config looks "filesystem_folder = /data". Otherwise you would have one more folder which is unnecessary, but thats just my opinion ;-)

**Comment by tomsquest** [comment]
Hi,

I think you should create the password/user file on your host, then put it in the config volume. Then you change the `config` file to point at it.
You won't `bcrypt` the password from the container.

For the sslpart, frontend like `caddyserver` does automatic https certification generation. Radicale does not even know about https, because Caddyserver does it easily for him.
If you don't use a webserver, then I have no clue. 

Thanks for the tips about the useless subdir of `/data`. I had trouble with this settings in the past, and I don't remember if this is due to it. I will think about it.

**Comment by tomsquest** [comment]
For the folder part, have a look at https://github.com/Kozea/Radicale/issues/528
Basically, I cannot set `filesystem_folder = /data` as a file would be created at `/`.

**Comment by dmtroyer** [comment]
This would be helpful to include in the Readme or wiki

**Comment by tomsquest** [comment]
Hi @dmtroyer , can you tell from this issue which part is relevant (bcrypt, /data folder) ?

Thanks
