### ISSUE TITLE
chown: /data: Permission denied

### ISSUE THREAD

**Issue by anobar** [tomsquest/docker-radicale#64]
Dear programmers

I was following the readme to establish radicale in a container. However, server was not accessible by web or thunderbird. Trying to enter the container interactively, I saw that initialising the container, some permission error occurs. More or less minimal command to launch the container looks like that:

$ sudo docker run -a STDERR --name radicale     -p 127.0.0.1:5232:5232     --cap-drop ALL     --cap-add CHOWN     --cap-add SETUID     --cap-add SETGID     --cap-add KILL     tomsquest/docker-radicale
chown: /data: Permission denied

Container is the established, but it looks, data it cannot provide. The experiment was run at Debian 10 buster.

How is the correct way to flawlessly run a radicale container?

Thanks, Axel

**Comment by tomsquest** [comment]
Hi @anobar ,

It is advised, and more, **expected** that you provide a /data directory as a volume. This directory is where your data will be stored. If you don't set this volume, the data will be **in** the container and may vanish when the container is removed.  

BTW the error you have is because the `cap-add`/`cap-drop` instructions restrict the reading of the `/data` directory inside the container.
